# Generated by Django 3.1.5 on 2021-01-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_card_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='cover_image',
            field=models.ImageField(default='images/pexels-fabio-scaletta-2115984.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
