# Generated by Django 3.1.5 on 2021-01-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deck_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='cover_image',
        ),
        migrations.AlterField(
            model_name='card',
            name='question_image',
            field=models.CharField(max_length=1000),
        ),
    ]
