# Generated by Django 3.1.5 on 2021-01-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210111_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='deck_cover',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
