# Generated by Django 3.1.5 on 2021-01-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210112_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='id',
            new_name='unique_id',
        ),
    ]
