# Generated by Django 3.1.5 on 2021-01-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210112_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='return_to_pile',
            field=models.BooleanField(default=False),
        ),
    ]
