# Generated by Django 3.1.5 on 2021-01-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210112_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='question_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='question_image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
