# Generated by Django 3.1.5 on 2021-01-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210112_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='deck_cover_upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
