# Generated by Django 3.1.5 on 2021-01-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_deck_deck_cover_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='question_image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
