# Generated by Django 3.1.5 on 2021-01-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_card_question_image_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='question_image_upload',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='deck_cover_upload',
        ),
    ]
