# Generated by Django 3.1.5 on 2021-01-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210112_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
