# Generated by Django 3.1.5 on 2021-01-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_deck_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(blank=True, choices=[('1', 'Mustard'), ('2', 'Blue'), ('3', 'Red'), ('4', 'Green')], default='1', help_text='Color Choice', max_length=1),
        ),
    ]
