# Generated by Django 3.1.5 on 2021-01-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.CharField(help_text='Enter the answer to the question. (Required)', max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='question_image',
            field=models.CharField(blank=True, help_text='Enter a url for question image. (Optioinal)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='question_image_upload',
            field=models.ImageField(blank=True, help_text='Upload an image for card question. (Optional)', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='question_text',
            field=models.CharField(blank=True, help_text='Enter your question in text form. (Optional, Default if no image)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='deck_cover',
            field=models.CharField(blank=True, help_text='Enter a url for a deck cover image. (Optioinal)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='deck_cover_upload',
            field=models.ImageField(blank=True, help_text='Upload an image for deck cover photo (Optional)', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(help_text='Enter a name to identify your deck. (Required)', max_length=100),
        ),
    ]
